package servent.message;

public enum MessageType {
	NEW_NODE, WELCOME, SORRY, UPDATE, POISON,
	REMOVE_NODE, SOFT_FAIL, HARD_FAIL, HARD_FAIL_CONFIRM, REORGANIZATION,
	TICK, TACK, GIVE_BACKUP,
	FILE_DENIED, FRIEND_REQUEST,
	FILE_ADD, FILE_ASK, FILE_TELL, FILE_REMOVE, FILE_GET,
	RA_REQUEST, RA_REPLY
}
